import os
import plistlib

cd = os.path.dirname(os.path.realpath(__file__))
codesnippets = (plistlib.readPlist(os.path.join(cd, cs)) for cs in os.listdir(cd) if cs.endswith('codesnippet'))
snippets = ((s['IDECodeSnippetTitle'], s['IDECodeSnippetContents']) for s in codesnippets)

with open(os.path.join(cd, 'readme.md'), 'w') as readme:
    readme.write('Checkout to: `~/Library/Developer/Xcode/UserData/CodeSnippets/`\n\n')
    for title, code in sorted(snippets, key=lambda s: s[0].lower()):
        readme.write('## %(title)s\n\n``` obj-c\n%(code)s\n```\n\n'%locals())
    readme.write('*Generated by readme.py: `python readme.py`*\n')
